### ISSUE TITLE
How to retrieve Alarm information?

### ISSUE THREAD

**Issue by jasonlim97xp** [xeonfusion/VSCaptureMP#12]
I want to be able to retrieve information of any alarms that are being triggered from the device. I noticed at Class2.cs there's definition of the following which corresponds to the numeric has an active alarm condition.

`public const int MSMT_STATE_IN_ALARM = 0x0002;`

However I don't see the it or MeasurementState being used. Anywhere I can add them in order to retrieve the information of the alarm?

**Comment by xeonfusion** [comment]
Retrieving alarm data needs the addition of more handling code but is possible if you follow the interface programming guidelines.

**Comment by jasonlim97xp** [comment]
Thanks a lot @xeonfusion, managed to get the alarm status by using the state value in the NuObsValue.
