### ISSUE TITLE
What type of data can be logged?

### ISSUE THREAD

**Issue by fli79** [xeonfusion/VSCaptureMP#3]
Hello! 

Thanks for writing this software! 

I have some questions:
- Is the GE B105 monitor supported? 
- Do you need any extra software such as iCollect?
- Which channels can be logged? Is time-information included? Which sampling rates?

**Comment by xeonfusion** [comment]
VSCaptureMP supports Philips Intellivue monitors, for GE monitors a different repo has to be used, see https://github.com/xeonfusion/VSCaptureWave and https://sourceforge.net/projects/vscapture/ . Modules run independently without need for additional software, captures numeric vital signs data with or without waveforms, polling rates can be chosen.

**Comment by fli79** [comment]
Thanks - I will have a look there
