### ISSUE TITLE
Post to aws lambda https

### ISSUE THREAD

**Issue by afigar** [xeonfusion/VSCaptureMP#4]

**Comment by afigar** [comment]
Is it possible for you to allow posting to https ? 
Something like this:
https://stackoverflow.com/questions/37869135/is-that-possible-to-send-httpwebrequest-using-tls1-2-on-net-4-0-framework
I'm not being able to post json data to a aws lambda function with uri https://xxxx.amazonaws.com/xxxx/api/v1/

**Comment by xeonfusion** [comment]
The JSON export did seem to work with https on testing. Could you check if your .NET framework is 4.5 or higher and update? What error message are you getting and which OS? Try adding SSL/TLS trusted certificates manually (get it from a browser) in case of Mono in Raspberry Pi. Does the AWS function need a passcode?

**Comment by xeonfusion** [comment]
Thanks for code suggestion [https://sourceforge.net/p/vscapture/discussion/general/thread/f1412ace2c/?limit=25](url). Should the code use |= to not turn off default security settings? [https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5](url)
