### ISSUE TITLE
Timestamps in CSV output is incorrect after about 1 hour of datalogging

### ISSUE THREAD

**Issue by wildcat37** [xeonfusion/VSCaptureMP#5]
I'm running the binary from sourceforge for datalogging from a Philips device via LAN. Saving to csv, calibrated data, 1 second data, data set option #2, which includes the pleth/spo2 data. About running for a little over an hour, I see that the CSV timestamp is wrong. The live spo2 data is correct however. 

this is how the csv file looks like with an incorrect time stamp
01/20/2021 22:09:43,72423680,97.4,77,2.1 # first line
.
.
.01/20/2021 23:21:15,106756352,97.5,58,12.5
01/20/2021 23:21:16,106764544,97.5,58,12.4
01/20/2021 22:09:42,106772736,97.5,58,12.3 # timestamp incorrect, rolls back about 1 hour
01/20/2021 22:09:43,106780928,97.5,58,12.2
01/20/2021 22:09:44,106789120,97.5,58,12

**Comment by xeonfusion** [comment]
The Intellivue protocol describes that behavior for relative time due to the use of 32 bit values for the relative time stamp, but the time stamp calculation code for absolute time needs to account for this. It uses the baseline relative timestamp but not the rollover, needs to be fixed. Alternatively you can change the source code to use the system or local computer time.

**Comment by wildcat37** [comment]
thanks for the insights, I will have a look at the protocol.

**Comment by wildcat37** [comment]
posting for future reference
I found that each increment in the relative time represents 125 microseconds.
To calculate the real absolute time, calculate the difference in relative time, multiply by 125e-6 to calculate "seconds" and add it to the timestamp from the first line in the csv file.

**Comment by xeonfusion** [comment]
The roll over bug may be related to not rechecking MDS monitor attributes regularly with a single poll for MDS attributes, to check if the mapping between Absolute and Relative timestamps is still valid. I have modified the code (binary attached) to do so, let me know if this fixes the issue.
[VSCaptureMPv1.008b1.zip](https://github.com/xeonfusion/VSCaptureMP/files/5880327/VSCaptureMPv1.008b1.zip)

**Comment by wildcat37** [comment]
I will be glad to run this test. I just started the datalogging, will run for about 8 hours and report back if all goes well.

Since I am not familiar with the protocol, I did not realize the rollback in the absolute time column was a bug. I just knew that I could add the difference in relative time to the very first timestamp to calculate the "real time" and that was good enough for me. 

But if the rollback is a bug, I am happy to contribute and run the test while the issue is fresh in memory.

**Comment by xeonfusion** [comment]
Absolute time stamps may roughly roll over after 71 minutes with a 32 bit relative time unit without the fix (the baseline absolute time was not getting updated). Please share the .raw debug file generated to verify the data, to xeonfusion at yahoo dot com.

**Comment by wildcat37** [comment]
Okay, will run for about 1.5 hours. I do not see a .raw file. but there is a MPrawoutput.txt file. Please confirm that this is what you need.

**Comment by xeonfusion** [comment]
The .txt file with LAN and .raw file with MIB interface can be used to debug, the .txt file is relevant.

**Comment by wildcat37** [comment]
Data is attached. 
The absolute time in the csv is still rolling back. 

[VSCaptureMPv1.008b1rollbackfix.zip](https://github.com/xeonfusion/VSCaptureMP/files/5881122/VSCaptureMPv1.008b1rollbackfix.zip)

**Comment by xeonfusion** [comment]
This seems a bit harder to debug than expected. Polling for new MDS attributes should have fixed the mapping between baseline absolute time and relative time but it still seems to roll back. The absolute time also rolls back before the 32 bit numbers are fully allotted. Might be a logic issue with current relative time and baseline relative time somehow being read as the same when it is not in PollPacketDecoder method! Still running tests.

**Comment by xeonfusion** [comment]
It seems to be a calculation issue of elapsed relative time (values were not cast properly as 64 bit double for calculation). The mapping between baseline absolute and relative timestamps using MDS attribute requests still needs to be verified. Try this binary if it solves the issue or if the loop back still occurs.
[VSCaptureMP_MIBv1.008b3fix.zip](https://github.com/xeonfusion/VSCaptureMP/files/5939404/VSCaptureMP_MIBv1.008b3fix.zip)

**Comment by xeonfusion** [comment]
Updated VSCaptureMP to v1.008 to address this absolute timestamp roll over issue.
