### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by remiconley** [xeonfusion/VSCaptureMP#6]
Good Evening, 

As a part of my Biomedical Engineering senior design project at the University of Florida we are utilizing parts of your open sourced VSCapture code. My team and I were wondering if there was any way you would be willing to provide us with sample VSCapture data to use to test our software and help with the progress of our project. 

Thank you in advance for your assistance, 
Remi Conley 
remi.conley@ufl.edu

**Comment by wildcat37** [comment]
What kind of data are you looking for?
I have 1 second, spo2/pleth data in csv.
I might be able to get ECG and RESP if you tell me what you are interested in.

**Comment by xeonfusion** [comment]
VSCapture can capture data from the Intellivue monitor in "Demo mode" as a .raw binary file, this can be used to simulate a monitor using virtual serial port emulator software and a terminal app like Realterm.
