### ISSUE TITLE
Sending a trigger to start non-invasive blood pressure capture 

### ISSUE THREAD

**Issue by fmenegui** [xeonfusion/VSCaptureMP#7]
I am using the VSCaptureMP to automate an acquisition protocol for a few patients. I would like to send a trigger signal to an IntelliVue MP40 device so it can start a non-invasive blood pressure capture, i.e., start inflating the cuff. Is there a way I could do this ?
Thank you.

**Comment by xeonfusion** [comment]
Currently VSCaptureMP can only download data from the monitor, commands are not supported, the protocol may not support this feature too.
