### ISSUE TITLE
how can i port this software to run under ARM linux ,such as rasberry pi 4 

### ISSUE THREAD

**Issue by ericdai** [xeonfusion/VSCaptureMP#8]
I want to port it to .net core 5.0 , but I can not find how to do it

**Comment by xeonfusion** [comment]
You can run VSCaptureMP on RaspberryPi by installing Mono runtime:
$ sudo apt-get install mono-complete

Then run the compiled binary with:
$ mono vscapturemp.exe

Porting the project to dot net core needs some minor modifications (to the JSON export dependency) but is possible, as most of the code is standard dot net. PM at xeonfusion at yahoo dot com if you need some starting project source.

**Comment by ericdai** [comment]
thanks for reply.
Is it that dotnet core is faster than mono? I still want to port it to dotnetcore ，could you please give me some suggestion for it？

**Comment by xeonfusion** [comment]
@ericdai I have ported the code to .NET 5.0, you can check out the repository here: https://github.com/xeonfusion/VSCaptureMPCore
