### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by patnatha** [xeonfusion/VSCaptureMP#9]
Just wanted to let you know that i took your program and used it for research in hemorrhagic shock for intellivue MP90. I have made some changes to post real time to our local redcap database and it works great! Dot Net 6 is awesome, i developed it on a Unix (Mac OSX) and then deployed it to a raspberry pi with a little cronjob. Now all our research anesthesia machine (3) continually log data. This is an excellent project and for people with a little coding experience, way better than things like VItalsDB or the more end to end solutions which are actually more difficult to use. THANKS!

https://github.com/patnatha/VSCaptureMP

**Comment by xeonfusion** [comment]
That’s great to hear and thanks for sharing your project, would like to read more about it, is there a blog/link about it? (please do cite VSCapture project if you found it useful). The dot net platform indeed makes it versatile, runs quite well on RaspberryPi. VSCapture has been used for several projects globally: https://www.linkedin.com/pulse/vscapture-globally-used-customizable-data-capture-john?trk=public_profile_article_view PM at xeonfusion at yahoo dot com.
